### ISSUE TITLE
add all openssl headers

### ISSUE THREAD

**Issue by Fabian-Sauer** [gematik/OpenSSL-Swift#10]
### Unaccessible openssl functions
We use your framework in our project to read eGK. This is an existing project that already uses openssl. We removed the existing dependencies to openssl and just use your framework. But in your framework there are some openssl functions missing. For instance OPENSSL_init or SMIME_read_PKCS7. Could you please add all openssl headers?

**Comment by mfiebig** [comment]
Thanks for your suggestion. Unfortunately, the purpose of this repository is not to serve as a complete wrapper for all OpenSSL functions. Instead, it aims to extend Apple's Crypto framework, which lacks certain cryptographic functionalities, such as BrainPool ECC.

We cannot create or maintain comprehensive coverage. I recommend that you fork this repository and add the missing functionality. SPM has a mirror function that could serve your fork instead of the original. If the changes are straightforward, we might consider incorporating the missing parts if you open a PR. However, we cannot make any guarantees, as we are also constrained by company-internal security measures when extending the library.

**Comment by Fabian-Sauer** [comment]
Ok, thanks for your response. We will think about your suggestions.
